homeassistant:
  name: Domov
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Prague
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

customizer:
  custom_ui: local

hacs:
  token: 263f9b741494794fa3e139dcdf60d2f83d2d73dc
  theme: true
  appdaemon: true

# Enables the frontend
frontend:
  javascript_version: latest
  #themes: !include themes.yaml
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

system_health:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #ssl_certificate: /etc/letsencrypt/fullchain.crt
  #ssl_key: /etc/letsencrypt/host.key

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

logger:
  default: info

# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Xiaomi Gateway
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomigw_key
      host: !secret xiaomigw_ip

# Z-Wave stick
zwave:
  usb_path: /dev/usbzwave
  network_key: !secret zwavenetwork_key

# Broadlink IR for Air Conditioning
switch:
  # Bedroom
  - platform: broadlink
    host: !secret broadlink_bedroom_host
    mac: !secret broadlink_bedroom_mac
  # Kids
  - platform: broadlink
    host: !secret broadlink_kids_host
    mac: !secret broadlink_kids_mac
  # Living
  - platform: broadlink
    host: !secret broadlink_living_host
    mac: !secret broadlink_living_mac

climate:
  - platform: smartir
    name: AC_bedroom
    unique_id: ac_bedroom
    device_code: 1402
    controller_data: !secret broadlink_bedroom_host
  - platform: smartir
    name: AC_kids
    unique_id: ac_kids
    device_code: 1402
    controller_data: !secret broadlink_kids_host
  - platform: smartir
    name: AC_living
    unique_id: ac_living
    device_code: 1402
    controller_data: !secret broadlink_living_host

smartir:

mqtt:
  discovery: true
  broker: 192.168.10.200
  certificate: /home/homeassistant/MQTTCAcert.pem
  client_id: homeassistant
  client_key: /home/homeassistant/MQTThassClient.key
  client_cert: /home/homeassistant/MQTThassClient.pem
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_apikey
  - name: pushbullet_jirka
    platform: pushbullet
    api_key: !secret pushbullet_apikey_jirka
  - name: pushover
    platform: pushover
    api_key: !secret pushover_apikey
    user_key: !secret pushover_userkey


#group: !include groups.yaml
automation: !include_dir_list automation 
script: !include scripts.yaml

input_boolean: !include input/boolean.yaml
#input_select: !include input/select.yaml
input_number: !include input/number.yaml
input_datetime: !include input/datetime.yaml

alert: !include_dir_named alerts

sensor: !include_dir_list sensors
binary_sensor: !include_dir_list binary_sensors

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 30
  purge_interval: 1

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave