alias: "Handle bedroom temperature - restore default (free days)"
trigger:
- platform: template
  value_template: '{{ states.sensor.today_minutes.state == states.sensor.bedroom_free_first_on.state }}'
- platform: template
  value_template: '{{ states.sensor.today_minutes.state == states.sensor.bedroom_free_first_off.state }}'
- platform: template
  value_template: '{{ states.sensor.today_minutes.state == states.sensor.bedroom_free_second_on.state }}'
- platform: template
  value_template: '{{ states.sensor.today_minutes.state == states.sensor.bedroom_free_second_off.state }}'
condition:
- condition: state
  entity_id: 'binary_sensor.workday_sensor'
  state: 'off'
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.thermostat_bedroom_keepauto
