alias: "Handle bedroom temperature override"
trigger:
- platform: state
  entity_id: sensor.thermostat_bedroom_target_temperature
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.sensor.thermostat_bedroom_target_temperature.state != states.input_number.bedroom_high_temperature.state }}'
    - condition: template
      value_template: '{{ states.sensor.thermostat_bedroom_target_temperature.state != states.input_number.bedroom_low_temperature.state }}'
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.thermostat_bedroom_keepauto
