# Heaty
alias: "Reschedule Heaty every 10 minutes (living)"
trigger:
- platform: time
  minutes: '/10'
  seconds: 40
condition:
- condition: state
  entity_id: 'input_boolean.thermostat_living_keepauto'
  state: 'on'
action:
  - event: heaty_reschedule
    event_data:
      room_name: living

