alias: Heating - turn off vacation (season on)
trigger:
  platform: state
  entity_id: input_boolean.vacation_mode
  from: 'on'
  to: 'off'
condition:
  condition: state
  entity_id: input_boolean.heating_season
  state: 'on'
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.heating_enabled