alias: Heating - turn on heating season (vacation off)
trigger:
  platform: state
  entity_id: input_boolean.heating_season
  from: 'off'
  to: 'on'
condition:
  condition: state
  entity_id: input_boolean.vacation_mode
  state: 'off'
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.heating_enabled