alias: Heating - turn off heating season
trigger:
  platform: state
  entity_id: input_boolean.heating_season
  from: 'on'
  to: 'off'
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.heating_enabled