alias: "Handle kids temperature override"
trigger:
- platform: state
  entity_id: sensor.thermostat_kids_target_temperature
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.sensor.thermostat_kids_target_temperature.state != states.input_number.kids_high_temperature.state }}'
    - condition: template
      value_template: '{{ states.sensor.thermostat_kids_target_temperature.state != states.input_number.kids_low_temperature.state }}'
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.thermostat_kids_keepauto
