alias: "Handle living temperature - restore default (work days)"
trigger:
- platform: template
  value_template: '{{ states.sensor.today_minutes.state == states.sensor.living_work_first_on.state }}'
- platform: template
  value_template: '{{ states.sensor.today_minutes.state == states.sensor.living_work_first_off.state }}'
- platform: template
  value_template: '{{ states.sensor.today_minutes.state == states.sensor.living_work_second_on.state }}'
- platform: template
  value_template: '{{ states.sensor.today_minutes.state == states.sensor.living_work_second_off.state }}'
condition:
- condition: state
  entity_id: 'binary_sensor.workday_sensor'
  state: 'on'
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.thermostat_living_keepauto
