# Xiaomi Gateway turn by Sun movement
#- id: sunrise_gw_on
alias: Turn on Gateway at sunset
trigger:
  platform: sun
  event: sunset
action:
  service: light.turn_on
  data:
    entity_id: light.gateway_light_7811dcb1f507
    brightness_pct : 2
    rgb_color : [255, 153, 33]
